apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cookies-ingress
spec:
  rules:
    - http:
        paths:
          - path: /preparation
            backend:
              serviceName: preparation
              servicePort: 8080

